apiVersion: v1
kind: Service
metadata:
  name: django-lb
spec:
  type: LoadBalancer
  ports:
  - name: django
    port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: django
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: django
spec:
  selector:
    matchLabels:
      app: django
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
    spec:
      initContainers:
      - name: check-mysql
        image: <YOUR_REPOSITORY>/mysql-client
        command: ["sh", "mysqladmin.sh"]
        env:
        - name: MYSQL_PASSWORD
          #value: password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
      containers:
      - image: <YOUR_REPOSITORY>/django
        name: django
        env:
        - name: MYSQL_USER
          #value: password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: MYSQL_PASSWORD
          #value: password
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          value: djk8s 
        ports:
        - containerPort: 8000
