apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_password: YOUR_ROOT_PASSWORD # with encode base64
  user: YOUR_USER_NAME # with encode base64
  password: YOUR_USER_PASSWORD # with encode base64
  db_name: YOUR_DB_NAME # with encode base64
